### ISSUE TITLE
Docs:  Show order of repeatable values in REPEATABLEVALUES function

### ISSUE THREAD

**Issue by MappingKat** [fulcrumapp/fulcrum-expressions#11]
Just thought it would be nice to add the ordering in the docs. 

http://www.fulcrumapp.com/developers/expressions/repeatablevalues/

**Comment by zhm** [comment]
What do you mean show the order?

**Comment by MappingKat** [comment]
I think I got a little confused as to if the right value is the first or last repeatable value. I would assume the least recent but am not positive.

**Comment by zhm** [comment]
I don't think there's anything to be done here.
