### ISSUE TITLE
GPS raw data fields in expressions

### ISSUE THREAD

**Issue by colemanm** [fulcrumapp/fulcrum-expressions#8]
Can we add a function to return the GPS data values in calculations?

* `gps_horizontal_accuracy` - GPSHORIZONTALACCURACY
* `gps_vertical_accuracy` - GPSVERTICALACCURACY
* `gps_speed` - GPSSPEED
* `gps_altitude` - GPSALTITUDE
* `gps_course` - GPSCOURSE

Something like those? Perhaps they would return NULL if evaluated from a device without access to them...

**Comment by zhm** [comment]
`CURRENTLOCATION()` should provide this data.
